baseURL: https://jsevedge.github.io
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
publishDir: public
theme: ananke
title: 'James Sevedge'
menu:
  main:
  - identifier: articles
    name: Articles
    title: Articles
    url: /post/
    weight: 100
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 110
params:
  background_color_class: bg-dark-gray # http://tachyons.io/docs/themes/skins/
  description: 'James Sevedge'
  featured_image: "/seattle_sunset.jpg"
  github: 'https://github.com/jsevedge'
  linkedin: 'http://linkedin.com/in/james-sevedge/'
  recent_posts_number: 1