baseURL: https://jsevedge.github.io
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
publishDir: public
theme: ananke
title: 'James Sevedge'
menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 100
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 110
params:
  favicon: '/hawaii.jpg'
  description: 'James Sevedge'
  github: 'https://github.com/jsevedge'
  linkedin: 'http://linkedin.com/in/james-sevedge/'
  background_color_class: bg-black # http://tachyons.io/docs/themes/skins/
  featured_image: "/motion_graphics.gif"
  recent_posts_number: 5