author:
  name: James Sevedge
  email: jjesc1031@gmail.com
baseURL: https://jamessevedge.com
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
publishDir: public
theme: custom
title: 'James Sevedge'
menu:
  main:
  - identifier: articles
    name: Articles
    title: Articles
    url: /articles/
    weight: 100
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 110
  - identifier: contact
    name: Contact
    title: Contact
    url: /contact/
    weight: 120
params:
  background_color_class: bg-dark-gray # http://tachyons.io/docs/themes/skins/
  featured_image: "/seattle_sunset.jpg"
  title_for_featured_image: false
  github: 'https://github.com/jsevedge'
  linkedin: 'http://linkedin.com/in/james-sevedge/'
  rss: 'default'
  recent_posts_number: 2
  google_analytics_id: 'G-Q5B427HWSJ' # Google Analytics 4 Measurement ID
markup:
  goldmark:
    renderer:
      unsafe: true